#see http://docs.spring.io/spring-boot/docs/1.5.2.RELEASE/reference/html/common-application-properties.html
info:
  version: "${project.version}"

spring:
  application:
    name: admin-service
  boot:
    admin:
      username: ${cloud.service.security.user.name}     #These two are needed so that the client
      password: ${cloud.service.security.user.password}   #can register at the protected server api
      client:
        metadata:
          user.name: ${cloud.service.security.user.name}        #These two are needed so that the server
          user.password: ${cloud.service.security.user.password}  #can access the proteceted client endpoints
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti

server:
  port: 8100


#security
security:
  basic:
    enabled: false
  user:
    name: ${cloud.service.security.user.name}
    password: ${cloud.service.security.user.password}
management:
  security:
    enabled: false

#eureka
eureka:
  server:
    hostname: ${cloud.eureka.server.hostname}
    username: ${cloud.eureka.server.username}
    password: ${cloud.eureka.server.password}
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: ${cloud.eureka.instance.prefer-ip-address}
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
        enabled: ${cloud.eureka.client.healthcheck.enabled}
    serviceUrl:
      defaultZone: http://${eureka.server.username}:${eureka.server.password}@${eureka.server.hostname}:8761/eureka/

#日志
logging:
  file: ${spring.application.name}.log
  path: .
  level:
    root: ${cloud.service.logging.level.root.info}