#see http://docs.spring.io/spring-boot/docs/1.5.2.RELEASE/reference/html/common-application-properties.html
spring:
  application:
    name: admin-service
  boot:
    admin:
      username: ${security.user.name}       #These two are needed so that the client
      password: ${security.user.password}   #can register at the protected server api
      client:
        metadata:
          user.name: ${security.user.name}        #These two are needed so that the server
          user.password: ${security.user.password}  #can access the proteceted client endpoints
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti

server:
  port: 8100


#security
security:
  basic:
    enabled: false
  user:
    name: louchen
    password: 123456
management:
  security:
    enabled: false

#eureka
eureka:
  server:
    hostname: 127.0.0.1
    username: louchen
    password: 123456
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://${eureka.server.username}:${eureka.server.password}@${eureka.server.hostname}:8761/eureka/

#日志
logging:
  file: ${spring.application.name}.log
  path: .
  level:
    root: info