#see http://docs.spring.io/spring-boot/docs/1.5.2.RELEASE/reference/html/common-application-properties.html
spring:
  application:
    name: business-service-${spring.cloud.config.profile}
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    enabled: true
    flush-interval: 1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

#security
security:
  basic:
    enabled: true
  user:
    name: linyinan
    password: 123456

#eureka
eureka:
  server:
    hostname: 127.0.0.1
    username: louchen
    password: 123456
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://${eureka.server.username}:${eureka.server.password}@${eureka.server.hostname}:8761/eureka/

#日志
logging:
  level:
    root: info