spring:
  application:
    name: zipkin-service
  datasource:
    schema: classpath:/zipkin.sql
    url: ${cloud.zipkin.mysql.url}
    username: ${cloud.zipkin.mysql.username}
    password: ${cloud.zipkin.mysql.password}
    # Switch this on to create the schema on startup:
    initialize: false
    continueOnError: true
    driver-class-name: com.mysql.jdbc.Driver
  sleuth:
    enabled: false
  rabbitmq:
      host: ${cloud.spring.rabbitmq.host}
      port: ${cloud.spring.rabbitmq.port}
      username: ${cloud.spring.rabbitmq.username}
      password: ${cloud.spring.rabbitmq.password}


zipkin:
  storage:
    type: mysql

server:
  port: 9412

#security
security:
  basic:
    enabled: true
  user:
    name: ${cloud.service.security.user.name}
    password: ${cloud.service.security.user.password}
management:
  security:
    enabled: false

#eureka
eureka:
  server:
    hostname: ${cloud.eureka.server.hostname}
    username: ${cloud.eureka.server.username}
    password: ${cloud.eureka.server.password}
  instance:
    prefer-ip-address: ${cloud.eureka.instance.prefer-ip-address}
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    healthcheck:
        enabled: ${cloud.eureka.client.healthcheck.enabled}
    serviceUrl:
      defaultZone: http://${eureka.server.username}:${eureka.server.password}@${eureka.server.hostname}:8761/eureka/

#日志
logging:
  file: ${spring.application.name}.log
  path: .
  level:
    root: ${cloud.service.logging.level.root.info}