spring:
  application:
    name: zipkin-service
  datasource:
    schema: classpath:/zipkin.sql
    url: jdbc:mysql://127.0.0.1:3306/zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    # Switch this on to create the schema on startup:
    initialize: false
    continueOnError: true
    driver-class-name: com.mysql.jdbc.Driver
  sleuth:
    enabled: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

zipkin:
  storage:
    type: mysql

server:
  port: 9412

#security
security:
  basic:
    enabled: true
  user:
    name: louchen
    password: 123456

#eureka
eureka:
  server:
    hostname: 127.0.0.1
    username: louchen
    password: 123456
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    healthcheck:
        enabled: true
    serviceUrl:
      defaultZone: http://${eureka.server.username}:${eureka.server.password}@${eureka.server.hostname}:8761/eureka/

#日志
logging:
  level:
    root: info