spring:
  application:
    name: eureka-server

server:
  port: 8761

#security
security:
  basic:
    enabled: true
  user:
    name: ${cloud.eureka.server.username}
    password: ${cloud.eureka.server.password}

#eureka
eureka:
  environment: ${cloud.eureka.environment}
  instance:
    hostname: ${cloud.eureka.server.hostname}
    prefer-ip-address: ${cloud.eureka.instance.prefer-ip-address}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

#日志
logging:
  file: ${spring.application.name}.log
  path: .
  level:
    root: ${cloud.service.logging.level.root.info}