spring:
  application:
    name: eureka-server
server:
  port: 8761
  undertow:
    accesslog:
      enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

