spring:
  application:
    name: eureka-server

server:
  port: 8761

#security
security:
  basic:
    enabled: true
  user:
    name: louchen
    password: 123456

#eureka
eureka:
  environment: develop
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

#日志
logging:
  level:
    root: info